name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go:
        - '1.22'
        - '1.23'
        size:
        - small
        - large

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -tags codegen,largetest -v ./...

    - name: Test (small)
      if: ${{ matrix.size == "small" }}
      run: go test -v ./...

    - name: Test (large)
      if: ${{ matrix.size == "large" }}
      run: go test -tags codegen,largetest -v ./...

    - name: Check generated data
      run: |
        go generate ./...
        git diff --exit-code || {
          echo 'please re-run go generate ./... and commit the changes'
          exit 1
        }
